#!/bin/bash

PACKAGES=(
  "pydocstyle"
  "pylint"
  "black"
  "osmnx"
  "networkx"
  "scikit-learn"
)

echo "Starting to check and install packages..."

for package in ${PACKAGES[@]}; do
  if ! python3 -c "import $package" &>/dev/null; then
    pip3 install $package
  fi
done
echo "All packages are installed."
