name: PyLint Runner

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        python3 -m venv environ
        environ/bin/python3 -m pip install --upgrade pip
        source environ/bin/activate
        bash install_reqs
    - name: Run Pylint
      run: |
        source environ/bin/activate
        pylint --output-format=colorized $(git ls-files './*.py')
